#pragma once 

#define SPEEX_GET_FRAME_SIZE 3
#define SPEEX_SET_QUALITY 4
#define SPEEX_SET_MODE 6
#define SPEEX_GET_MODE 7
#define SPEEX_SET_LOW_MODE 8
#define SPEEX_GET_LOW_MODE 9
#define SPEEX_SET_VBR 12
#define SPEEX_GET_VBR 13
#define SPEEX_SET_VBR_QUALITY 14
#define SPEEX_GET_VBR_QUALITY 15
#define SPEEX_SET_COMPLEXITY 16
#define SPEEX_GET_COMPLEXITY 17
#define SPEEX_SET_BITRATE 18
#define SPEEX_GET_BITRATE 19
#define SPEEX_SET_SAMPLING_RATE 24
#define SPEEX_GET_SAMPLING_RATE 25
#define SPEEX_RESET_STATE 26
#define SPEEX_GET_RELATIVE_QUALITY 29
#define SPEEX_SET_VAD 30
#define SPEEX_GET_VAD 31
#define SPEEX_SET_ABR 32
#define SPEEX_GET_ABR 33
#define SPEEX_SET_DTX 34
#define SPEEX_GET_DTX 35
#define SPEEX_SET_SUBMODE_ENCODING 36
#define SPEEX_GET_SUBMODE_ENCODING 37
#define SPEEX_GET_LOOKAHEAD 39


#define SPEEX_SET_PLC_TUNING 40
#define SPEEX_GET_PLC_TUNING 41

#define SPEEX_SET_VBR_MAX_BITRATE 42
#define SPEEX_GET_VBR_MAX_BITRATE 43

#define SPEEX_SET_HIGHPASS 44
#define SPEEX_GET_HIGHPASS 45

#define SPEEX_GET_PI_GAIN 100
#define SPEEX_GET_EXC     101
#define SPEEX_SET_INNOVATION_SAVE   104
#define SPEEX_SET_WIDEBAND   105
#define SPEEX_GET_STACK   106